# Welcome back 😁 😁
### So far in this week you have learned:


*   What is a programming language and why python
*   Variables and functions in python
*   Conditions and for loops in python
*   OOP in python

### Let's know more about python 👇 👇



*   Lists in python
*   Numpy arrays
*   Pandas







## What is a list

Lists are used to store multiple items in a single variable ✅ ✅

In python lists could contain any type of items such as integer or string

## Let's see an example

In [23]:
my_list = ["python", "java", "c"]
print(my_list)

['python', 'java', 'c']


In [24]:
my_list = [1, "SPARK", 100, "python"]
print(my_list)

[1, 'SPARK', 100, 'python']


## How to get an item from the list

let's say we have this list   
[python, jave, c]

Each item have an index that we could use to get this item. we start with zero until the end of the list

So python will have an index of 0, jave will have an index of 1, and c will have an index of 3





![picture](https://favtutor.com/resources/images/uploads/mceu_51042390911678942910142.png)



In [25]:
my_list = ["python", "java", "c"]

# TO DO .. Get the sesond element from the list

my_list[1]

'java'

## Also, you can easily know the length of the list

In [26]:
# TO DO .. Get the length of the list

len(my_list)

3

## Of course you can add items or remove items from your list

### Let's see

In [27]:
my_list = ["python", "java", "c"]

my_list.append("c++") # add an item "c++" to the list

print(my_list)

['python', 'java', 'c', 'c++']


In [28]:
# you can also use .insert to add to a specific place in the list

my_list = ["python", "java", "c"]

my_list.insert(1, "c++")

my_list

['python', 'c++', 'java', 'c']

In [29]:
# TO DO .. remove the item "jave" from the list

my_list.remove("java")

my_list

['python', 'c++', 'c']

## Numpy arrays

![picture](https://miro.medium.com/v2/resize:fit:1400/1*X0Dg7QfSYtWhSAu-afi8-g.png)


### It could be 1D, 2D, or 3D of items, but let's see the simple 1D numpy array



### NumPy is a Python library

We need to import it to be able to use it

In [30]:
import numpy as np

In [31]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Why numpy .. why not a simple python list

numpy has very powerfull neumerical functions that we will see some of them, and also it's faster that python lists

In [32]:
# in numpy you can create a list of zeros or ones with any length very easily

# TO DO create a list that contains 20 zeros

my_np_array = np.zeros(20)
my_np_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [33]:
# TO DO create a list that contains 20 ones

my_np_array = np.ones(20)
my_np_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [34]:
# you can get part of the array by the indexs ... you can do it with python lists too, Go try it

my_np_array = np.array([1, 2, 3, 4, 5, 6, 7])
my_np_array[1:5]

array([2, 3, 4, 5])

In [35]:
# to konw the length of the array

my_np_array = np.array([1, 2, 3, 4, 5, 6, 7])
# TO DO .. get the shape of the array
len(my_np_array)


7

In [36]:
# add two arrays together

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1,arr2))   # TO DO .. concatinate the two arrays

arr

array([1, 2, 3, 4, 5, 6])

In [37]:
# you can also search in the array

arr = np.array([4, 2, 3, 6, 5, 4, 2])

x = np.where(arr == 4)

x

(array([0, 5]),)

In [38]:
# you can sort the array   ... You can do this with python lists .. Search about how

arr = np.array([4, 2, 3, 6, 5, 4, 2])

# TO DO .. sort the array
np.sort(arr)


array([2, 2, 3, 4, 4, 5, 6])

In [39]:
# let's convert a python list to numpy

python_list = [1, 2, 3, 4]

np_arr = np.array(python_list)

np_arr

array([1, 2, 3, 4])

In [40]:
# let's see if we need to get the maximum of the array

arr = np.array([4, 2, 3, 6, 5, 4, 2])

np.max(arr)

6

In [41]:
# what if we need the indexif this maximum

arr = np.array([4, 2, 3, 6, 5, 4, 2])

np.argmax(arr)

3

In [42]:
# TO DO ..

minimum = np.min(arr)  # get the minimum of the array
min_index = np.argmin(arr)  # get the index of the minimum value

mean= np.mean(arr)   # get the mean of the array
print(minimum)
print(min_index)
print(mean)


2
1
3.7142857142857144


In [43]:
# what if we have an array and wants to add a value of 3 to each item

# TO DO add 3 to each element of the array

arr = np.array([4, 2, 3, 6, 5, 4, 2])

new_array = np.add(arr,3)

new_array

array([7, 5, 6, 9, 8, 7, 5])

## Let's see what is pandas

Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning and exploring data

### we need first to inport it

In [44]:
import pandas as pd

In [45]:
# let's say we have a data for the number of users for each programming language in SPARK

mydataset = {
  'language': ["python", "c++", "java"],
  'number': [200, 20, 3]
}

my_pd = pd.DataFrame(mydataset)

my_pd

language  number
0   python     200
1      c++      20
2     java       3

In [47]:
!pwd

/home/shirshak/0 0 0 0SPARK AI academy/Week 1/Week 1-3 _ Scientific Programming with Python/Assignment


In [49]:
# what if we have larger data srored in a csv file .. let's read it

data = pd.read_csv("user.csv")    # TO DO .. read the CSV file called users.csv

data

user id  age gender     occupation zip code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [51]:
# TO DO .. get the first few rows from the data

data.head(6)

user id  age gender  occupation zip code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213
5        6   42      M   executive    98101

In [52]:
# TO DO .. get info about the data


data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   user id     943 non-null    int64 
 1   age         943 non-null    int64 
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB


In [53]:
# TO DO .. get the column names in the user's data

data.columns

Index(['user id', 'age', 'gender', 'occupation', 'zip code'], dtype='object')

In [55]:
# TO DO .. get the mean of the ages for all the users

data['age'].mean()

34.05196182396607

In [56]:
# TO DO .. get all the rows when the user's ages are less than 30

data[data['age']>30]


user id  age gender     occupation zip code
1          2   53      F          other    94043
4          5   33      F          other    15213
5          6   42      M      executive    98101
6          7   57      M  administrator    91344
7          8   36      M  administrator    05201
..       ...  ...    ...            ...      ...
934      935   42      M         doctor    66221
936      937   48      M       educator    98072
937      938   38      F     technician    55038
939      940   32      M  administrator    02215
941      942   48      F      librarian    78209

[495 rows x 5 columns]